# استخدم نسخة بايثون مناسبة
FROM python:3.11-slim

# ضبط مكان الكود داخل الـ Container
WORKDIR /code

# نسخ ملف المكتبات وتثبيتها
COPY ./requirements.txt /code/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

# نسخ باقي ملفات المشروع
COPY . .

# Hugging Face Spaces بيستخدم بورت 7860 افتراضياً
CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "7860"]